export const NIGERIA_STATES = [
  { name: 'Abia', code: 'AB', lgas: [
    { name: 'Aba North', code: 'ABN' },
    { name: 'Aba South', code: 'ABS' },
    { name: 'Arochukwu', code: 'ARO' },
    { name: 'Bende', code: 'BEN' },
    { name: 'Ikwuano', code: 'IKW' },
    { name: 'Isiala Ngwa North', code: 'ISN' },
    { name: 'Isiala Ngwa South', code: 'ISS' },
    { name: 'Isuikwuato', code: 'ISU' },
    { name: 'Obi Ngwa', code: 'OBN' },
    { name: 'Ohafia', code: 'OHA' },
    { name: 'Osisioma', code: 'OSI' },
    { name: 'Ugwunagbo', code: 'UGW' },
    { name: 'Ukwa East', code: 'UKE' },
    { name: 'Ukwa West', code: 'UKW' },
    { name: 'Umuahia North', code: 'UMN' },
    { name: 'Umuahia South', code: 'UMS' },
    { name: 'Umu Nneochi', code: 'UMU' },
  ] },
  { name: 'Adamawa', code: 'AD', lgas: [
    { name: 'Demsa', code: 'DEM' },
    { name: 'Fufore', code: 'FUF' },
    { name: 'Ganye', code: 'GAN' },
    { name: 'Gayuk', code: 'GAY' },
    { name: 'Gombi', code: 'GOM' },
    { name: 'Grie', code: 'GRI' },
    { name: 'Hong', code: 'HON' },
    { name: 'Jada', code: 'JAD' },
    { name: 'Lamurde', code: 'LAM' },
    { name: 'Madagali', code: 'MAD' },
    { name: 'Maiha', code: 'MAI' },
    { name: 'Mayo-Belwa', code: 'MAY' },
    { name: 'Michika', code: 'MIC' },
    { name: 'Mubi North', code: 'MUN' },
    { name: 'Mubi South', code: 'MUS' },
    { name: 'Numan', code: 'NUM' },
    { name: 'Shelleng', code: 'SHE' },
    { name: 'Song', code: 'SON' },
    { name: 'Toungo', code: 'TOU' },
    { name: 'Yola North', code: 'YON' },
    { name: 'Yola South', code: 'YOS' },
  ] },
  { name: 'Akwa Ibom', code: 'AK', lgas: [
    { name: 'Abak', code: 'ABA' },
    { name: 'Eastern Obolo', code: 'EAS' },
    { name: 'Eket', code: 'EKE' },
    { name: 'Esit Eket', code: 'ESI' },
    { name: 'Essien Udim', code: 'ESS' },
    { name: 'Etim Ekpo', code: 'ETI' },
    { name: 'Etinan', code: 'ETN' },
    { name: 'Ibeno', code: 'IBE' },
    { name: 'Ibesikpo Asutan', code: 'IBS' },
    { name: 'Ibiono-Ibom', code: 'IBI' },
    { name: 'Ika', code: 'IKA' },
    { name: 'Ikono', code: 'IKO' },
    { name: 'Ikot Abasi', code: 'IKA' },
    { name: 'Ikot Ekpene', code: 'IKE' },
    { name: 'Ini', code: 'INI' },
    { name: 'Itu', code: 'ITU' },
    { name: 'Mbo', code: 'MBO' },
    { name: 'Mkpat-Enin', code: 'MKP' },
    { name: 'Nsit-Atai', code: 'NSA' },
    { name: 'Nsit-Ibom', code: 'NSI' },
    { name: 'Nsit-Ubium', code: 'NSU' },
    { name: 'Obot Akara', code: 'OBA' },
    { name: 'Okobo', code: 'OKO' },
    { name: 'Onna', code: 'ONN' },
    { name: 'Oron', code: 'ORO' },
    { name: 'Oruk Anam', code: 'ORA' },
    { name: 'Udung-Uko', code: 'UDU' },
    { name: 'Ukanafun', code: 'UKA' },
    { name: 'Uruan', code: 'URU' },
    { name: 'Urue-Offong/Oruko', code: 'URO' },
    { name: 'Uyo', code: 'UYO' },
  ] },
  { name: 'Anambra', code: 'AN', lgas: [
    { name: 'Aguata', code: 'AGU' },
    { name: 'Anambra East', code: 'ANE' },
    { name: 'Anambra West', code: 'ANW' },
    { name: 'Anaocha', code: 'ANA' },
    { name: 'Awka North', code: 'AWN' },
    { name: 'Awka South', code: 'AWS' },
    { name: 'Ayamelum', code: 'AYA' },
    { name: 'Dunukofia', code: 'DUN' },
    { name: 'Ekwusigo', code: 'EKW' },
    { name: 'Idemili North', code: 'IDN' },
    { name: 'Idemili South', code: 'IDS' },
    { name: 'Ihiala', code: 'IHI' },
    { name: 'Njikoka', code: 'NJI' },
    { name: 'Nnewi North', code: 'NNN' },
    { name: 'Nnewi South', code: 'NNS' },
    { name: 'Ogbaru', code: 'OGB' },
    { name: 'Onitsha North', code: 'ONN' },
    { name: 'Onitsha South', code: 'ONS' },
    { name: 'Orumba North', code: 'ORN' },
    { name: 'Orumba South', code: 'ORS' },
    { name: 'Oyi', code: 'OYI' },
  ] },
  { name: 'Bauchi', code: 'BA', lgas: [
    { name: 'Alkaleri', code: 'ALK' },
    { name: 'Bauchi', code: 'BAU' },
    { name: 'Bogoro', code: 'BOG' },
    { name: 'Damban', code: 'DAM' },
    { name: 'Darazo', code: 'DAR' },
    { name: 'Dass', code: 'DAS' },
    { name: 'Gamawa', code: 'GAM' },
    { name: 'Ganjuwa', code: 'GAN' },
    { name: 'Giade', code: 'GIA' },
    { name: 'Itas/Gadau', code: 'ITA' },
    { name: 'Jama\'are', code: 'JAM' },
    { name: 'Katagum', code: 'KAT' },
    { name: 'Kirfi', code: 'KIR' },
    { name: 'Misau', code: 'MIS' },
    { name: 'Ningi', code: 'NIN' },
    { name: 'Shira', code: 'SHI' },
    { name: 'Tafawa Balewa', code: 'TAF' },
    { name: 'Toro', code: 'TOR' },
    { name: 'Warji', code: 'WAR' },
    { name: 'Zaki', code: 'ZAK' },
  ] },
  { name: 'Bayelsa', code: 'BY', lgas: [
    { name: 'Brass', code: 'BRA' },
    { name: 'Ekeremor', code: 'EKE' },
    { name: 'Kolokuma/Opokuma', code: 'KOL' },
    { name: 'Nembe', code: 'NEM' },
    { name: 'Ogbia', code: 'OGB' },
    { name: 'Sagbama', code: 'SAG' },
    { name: 'Southern Ijaw', code: 'SOU' },
    { name: 'Yenagoa', code: 'YEN' },
  ] },
  { name: 'Benue', code: 'BE', lgas: [
    { name: 'Ado', code: 'ADO' },
    { name: 'Agatu', code: 'AGA' },
    { name: 'Apa', code: 'APA' },
    { name: 'Buruku', code: 'BUR' },
    { name: 'Gboko', code: 'GBO' },
    { name: 'Guma', code: 'GUM' },
    { name: 'Gwer East', code: 'GWE' },
    { name: 'Gwer West', code: 'GWW' },
    { name: 'Katsina-Ala', code: 'KAT' },
    { name: 'Konshisha', code: 'KON' },
    { name: 'Kwande', code: 'KWA' },
    { name: 'Logo', code: 'LOG' },
    { name: 'Makurdi', code: 'MAK' },
    { name: 'Obi', code: 'OBI' },
    { name: 'Ogbadibo', code: 'OGB' },
    { name: 'Ohimini', code: 'OHI' },
    { name: 'Oju', code: 'OJU' },
    { name: 'Okpokwu', code: 'OKP' },
    { name: 'Oturkpo', code: 'OTU' },
    { name: 'Tarka', code: 'TAR' },
    { name: 'Ukum', code: 'UKU' },
    { name: 'Ushongo', code: 'USH' },
    { name: 'Vandeikya', code: 'VAN' },
  ] },
  { name: 'Borno', code: 'BO', lgas: [
    { name: 'Abadam', code: 'ABA' },
    { name: 'Askira/Uba', code: 'ASK' },
    { name: 'Bama', code: 'BAM' },
    { name: 'Bayo', code: 'BAY' },
    { name: 'Biu', code: 'BIU' },
    { name: 'Chibok', code: 'CHI' },
    { name: 'Damboa', code: 'DAM' },
    { name: 'Dikwa', code: 'DIK' },
    { name: 'Gubio', code: 'GUB' },
    { name: 'Guzamala', code: 'GUZ' },
    { name: 'Gwoza', code: 'GWO' },
    { name: 'Hawul', code: 'HAW' },
    { name: 'Jere', code: 'JER' },
    { name: 'Kaga', code: 'KAG' },
    { name: 'Kala/Balge', code: 'KAL' },
    { name: 'Konduga', code: 'KON' },
    { name: 'Kukawa', code: 'KUK' },
    { name: 'Kwaya Kusar', code: 'KWA' },
    { name: 'Mafa', code: 'MAF' },
    { name: 'Magumeri', code: 'MAG' },
    { name: 'Maiduguri', code: 'MAI' },
    { name: 'Marte', code: 'MAR' },
    { name: 'Mobbar', code: 'MOB' },
    { name: 'Monguno', code: 'MON' },
    { name: 'Ngala', code: 'NGA' },
    { name: 'Nganzai', code: 'NGA' },
    { name: 'Shani', code: 'SHA' },
  ] },
  { name: 'Cross River', code: 'CR', lgas: [
    { name: 'Abi', code: 'ABI' },
    { name: 'Akamkpa', code: 'AKA' },
    { name: 'Akpabuyo', code: 'AKP' },
    { name: 'Bakassi', code: 'BAK' },
    { name: 'Bekwarra', code: 'BEK' },
    { name: 'Biase', code: 'BIA' },
    { name: 'Boki', code: 'BOK' },
    { name: 'Calabar Municipal', code: 'CAM' },
    { name: 'Calabar South', code: 'CAS' },
    { name: 'Etung', code: 'ETU' },
    { name: 'Ikom', code: 'IKO' },
    { name: 'Obanliku', code: 'OBA' },
    { name: 'Obubra', code: 'OBU' },
    { name: 'Obudu', code: 'OBD' },
    { name: 'Odukpani', code: 'ODU' },
    { name: 'Ogoja', code: 'OGO' },
    { name: 'Yakuur', code: 'YAK' },
    { name: 'Yala', code: 'YAL' },
  ] },
  { name: 'Delta', code: 'DE', lgas: [
    { name: 'Aniocha North', code: 'ANI' },
    { name: 'Aniocha South', code: 'ANS' },
    { name: 'Bomadi', code: 'BOM' },
    { name: 'Burutu', code: 'BUR' },
    { name: 'Ethiope East', code: 'ETE' },
    { name: 'Ethiope West', code: 'ETW' },
    { name: 'Ika North East', code: 'IKN' },
    { name: 'Ika South', code: 'IKS' },
    { name: 'Isoko North', code: 'ISN' },
    { name: 'Isoko South', code: 'ISS' },
    { name: 'Ndokwa East', code: 'NDE' },
    { name: 'Ndokwa West', code: 'NDW' },
    { name: 'Okpe', code: 'OKP' },
    { name: 'Oshimili North', code: 'OSN' },
    { name: 'Oshimili South', code: 'OSS' },
    { name: 'Patani', code: 'PAT' },
    { name: 'Sapele', code: 'SAP' },
    { name: 'Udu', code: 'UDU' },
    { name: 'Ughelli North', code: 'UGN' },
    { name: 'Ughelli South', code: 'UGS' },
    { name: 'Ukwuani', code: 'UKW' },
    { name: 'Uvwie', code: 'UVW' },
    { name: 'Warri North', code: 'WAN' },
    { name: 'Warri South', code: 'WAS' },
    { name: 'Warri South West', code: 'WAS' },
  ] },
  { name: 'Ebonyi', code: 'EB', lgas: [
    { name: 'Abakaliki', code: 'ABA' },
    { name: 'Afikpo North', code: 'AFN' },
    { name: 'Afikpo South', code: 'AFS' },
    { name: 'Ebonyi', code: 'EBO' },
    { name: 'Ezza North', code: 'EZN' },
    { name: 'Ezza South', code: 'EZS' },
    { name: 'Ikwo', code: 'IKW' },
    { name: 'Ishielu', code: 'ISH' },
    { name: 'Ivo', code: 'IVO' },
    { name: 'Izzi', code: 'IZZ' },
    { name: 'Ohaozara', code: 'OHA' },
    { name: 'Ohaukwu', code: 'OHU' },
    { name: 'Onicha', code: 'ONI' },
  ] },
  { name: 'Edo', code: 'ED', lgas: [
    { name: 'Akoko-Edo', code: 'AKO' },
    { name: 'Egor', code: 'EGO' },
    { name: 'Esan Central', code: 'ESC' },
    { name: 'Esan North-East', code: 'ESN' },
    { name: 'Esan South-East', code: 'ESS' },
    { name: 'Esan West', code: 'ESW' },
    { name: 'Etsako Central', code: 'ETC' },
    { name: 'Etsako East', code: 'ETE' },
    { name: 'Etsako West', code: 'ETW' },
    { name: 'Igueben', code: 'IGU' },
    { name: 'Ikpoba Okha', code: 'IKP' },
    { name: 'Oredo', code: 'ORE' },
    { name: 'Orhionmwon', code: 'ORH' },
    { name: 'Ovia North-East', code: 'OVN' },
    { name: 'Ovia South-West', code: 'OVS' },
    { name: 'Owan East', code: 'OWE' },
    { name: 'Owan West', code: 'OWW' },
    { name: 'Uhunmwonde', code: 'UHU' },
  ] },
  { name: 'Ekiti', code: 'EK', lgas: [
    { name: 'Ado Ekiti', code: 'ADO' },
    { name: 'Efon', code: 'EFO' },
    { name: 'Ekiti East', code: 'EKE' },
    { name: 'Ekiti South-West', code: 'EKS' },
    { name: 'Ekiti West', code: 'EKW' },
    { name: 'Emure', code: 'EMU' },
    { name: 'Gbonyin', code: 'GBO' },
    { name: 'Ido Osi', code: 'IDO' },
    { name: 'Ijero', code: 'IJE' },
    { name: 'Ikere', code: 'IKE' },
    { name: 'Ikole', code: 'IKO' },
    { name: 'Ilejemeje', code: 'ILE' },
    { name: 'Irepodun/Ifelodun', code: 'IRE' },
    { name: 'Ise/Orun', code: 'ISE' },
    { name: 'Moba', code: 'MOB' },
    { name: 'Oye', code: 'OYE' },
  ] },
  { name: 'Enugu', code: 'EN', lgas: [
    { name: 'Aninri', code: 'ANI' },
    { name: 'Awgu', code: 'AWG' },
    { name: 'Enugu East', code: 'ENE' },
    { name: 'Enugu North', code: 'ENN' },
    { name: 'Enugu South', code: 'ENS' },
    { name: 'Ezeagu', code: 'EZE' },
    { name: 'Igbo Etiti', code: 'IGB' },
    { name: 'Igbo Eze North', code: 'IGN' },
    { name: 'Igbo Eze South', code: 'IGS' },
    { name: 'Isi Uzo', code: 'ISI' },
    { name: 'Nkanu East', code: 'NKE' },
    { name: 'Nkanu West', code: 'NKW' },
    { name: 'Nsukka', code: 'NSU' },
    { name: 'Oji River', code: 'OJI' },
    { name: 'Udenu', code: 'UDE' },
    { name: 'Udi', code: 'UDI' },
    { name: 'Uzo Uwani', code: 'UZO' },
  ] },
  { name: 'Federal Capital Territory', code: 'FC', lgas: [
    { name: 'Abaji', code: 'ABA' },
    { name: 'Abuja Municipal Area Council', code: 'AMC' },
    { name: 'Gwagwalada', code: 'GWA' },
    { name: 'Kuje', code: 'KUJ' },
    { name: 'Kwali', code: 'KWA' },
    { name: 'Kwali', code: 'KWA' },
  ] },
  { name: 'Gombe', code: 'GO', lgas: [
    { name: 'Akko', code: 'AKK' },
    { name: 'Balanga', code: 'BAL' },
    { name: 'Billiri', code: 'BIL' },
    { name: 'Dukku', code: 'DUK' },
    { name: 'Funakaye', code: 'FUN' },
    { name: 'Gombe', code: 'GOM' },
    { name: 'Kaltungo', code: 'KAL' },
    { name: 'Kwami', code: 'KWA' },
    { name: 'Nafada', code: 'NAF' },
    { name: 'Shongom', code: 'SHO' },
    { name: 'Yamaltu/Deba', code: 'YAM' },
  ] },
  { name: 'Imo', code: 'IM', lgas: [
    { name: 'Aboh Mbaise', code: 'ABO' },
    { name: 'Ahiazu Mbaise', code: 'AHI' },
    { name: 'Ehime Mbano', code: 'EHI' },
    { name: 'Ezinihitte', code: 'EZI' },
    { name: 'Ideato North', code: 'IDN' },
    { name: 'Ideato South', code: 'IDS' },
    { name: 'Ihitte/Uboma', code: 'IHI' },
    { name: 'Ikeduru', code: 'IKE' },
    { name: 'Isiala Mbano', code: 'ISI' },
    { name: 'Isu', code: 'ISU' },
    { name: 'Mbaitoli', code: 'MBA' },
    { name: 'Ngor Okpala', code: 'NGO' },
    { name: 'Njaba', code: 'NJA' },
    { name: 'Nkwerre', code: 'NKE' },
    { name: 'Nwangele', code: 'NWA' },
    { name: 'Obowo', code: 'OBO' },
    { name: 'Oguta', code: 'OGU' },
    { name: 'Ohaji/Egbema', code: 'OHA' },
    { name: 'Okigwe', code: 'OKI' },
    { name: 'Orlu', code: 'ORL' },
    { name: 'Orsu', code: 'ORS' },
    { name: 'Oru East', code: 'ORE' },
    { name: 'Oru West', code: 'ORW' },
    { name: 'Owerri Municipal', code: 'OWM' },
    { name: 'Owerri North', code: 'OWN' },
    { name: 'Owerri West', code: 'OWW' },
    { name: 'Unuimo', code: 'UNU' },
  ] },
  { name: 'Jigawa', code: 'JI', lgas: [
    { name: 'Auyo', code: 'AUY' },
    { name: 'Babura', code: 'BAB' },
    { name: 'Biriniwa', code: 'BIR' },
    { name: 'Birnin Kudu', code: 'BIK' },
    { name: 'Buji', code: 'BUJ' },
    { name: 'Dutse', code: 'DUT' },
    { name: 'Gagarawa', code: 'GAG' },
    { name: 'Garki', code: 'GAR' },
    { name: 'Gumel', code: 'GUM' },
    { name: 'Guri', code: 'GUR' },
    { name: 'Gwaram', code: 'GWA' },
    { name: 'Gwiwa', code: 'GWI' },
    { name: 'Hadejia', code: 'HAD' },
    { name: 'Jahun', code: 'JAH' },
    { name: 'Kafin Hausa', code: 'KAF' },
    { name: 'Kaugama', code: 'KAU' },
    { name: 'Kazaure', code: 'KAZ' },
    { name: 'Kiri Kasama', code: 'KIR' },
    { name: 'Kiyawa', code: 'KIY' },
    { name: 'Maigatari', code: 'MAI' },
    { name: 'Malam Madori', code: 'MAL' },
    { name: 'Miga', code: 'MIG' },
    { name: 'Ringim', code: 'RIN' },
    { name: 'Roni', code: 'RON' },
    { name: 'Sule Tankarkar', code: 'SUL' },
    { name: 'Taura', code: 'TAU' },
    { name: 'Yankwashi', code: 'YAN' },
  ] },
  { name: 'Kaduna', code: 'KD', lgas: [
    { name: 'Birnin Gwari', code: 'BIG' },
    { name: 'Chikun', code: 'CHI' },
    { name: 'Giwa', code: 'GIW' },
    { name: 'Igabi', code: 'IGA' },
    { name: 'Ikara', code: 'IKA' },
    { name: 'Jaba', code: 'JAB' },
    { name: 'Jema\'a', code: 'JEM' },
    { name: 'Kachia', code: 'KAC' },
    { name: 'Kaduna North', code: 'KAN' },
    { name: 'Kaduna South', code: 'KAS' },
    { name: 'Kagarko', code: 'KAG' },
    { name: 'Kajuru', code: 'KAJ' },
    { name: 'Kaura', code: 'KAU' },
    { name: 'Kauru', code: 'KAR' },
    { name: 'Kubau', code: 'KUB' },
    { name: 'Kudan', code: 'KUD' },
    { name: 'Lere', code: 'LER' },
    { name: 'Makarfi', code: 'MAK' },
    { name: 'Sabon Gari', code: 'SAG' },
    { name: 'Sanga', code: 'SAN' },
    { name: 'Soba', code: 'SOB' },
    { name: 'Zangon Kataf', code: 'ZAN' },
    { name: 'Zaria', code: 'ZAR' },
  ] },
  { name: 'Kano', code: 'KN', lgas: [
    { name: 'Ajingi', code: 'AJI' },
    { name: 'Albasu', code: 'ALB' },
    { name: 'Bagwai', code: 'BAG' },
    { name: 'Bebeji', code: 'BEB' },
    { name: 'Bichi', code: 'BIC' },
    { name: 'Bunkure', code: 'BUN' },
    { name: 'Dala', code: 'DAL' },
    { name: 'Dambatta', code: 'DAM' },
    { name: 'Dawakin Kudu', code: 'DAK' },
    { name: 'Dawakin Tofa', code: 'DAT' },
    { name: 'Doguwa', code: 'DOG' },
    { name: 'Fagge', code: 'FAG' },
    { name: 'Gabasawa', code: 'GAB' },
    { name: 'Garko', code: 'GAR' },
    { name: 'Garum Mallam', code: 'GAM' },
    { name: 'Gaya', code: 'GAY' },
    { name: 'Gezawa', code: 'GEZ' },
    { name: 'Gwale', code: 'GWA' },
    { name: 'Gwarzo', code: 'GWR' },
    { name: 'Kabo', code: 'KAB' },
    { name: 'Kano Municipal', code: 'KAM' },
    { name: 'Karaye', code: 'KAR' },
    { name: 'Kibiya', code: 'KIB' },
    { name: 'Kiru', code: 'KIR' },
    { name: 'Kumbotso', code: 'KUM' },
    { name: 'Kunchi', code: 'KUN' },
    { name: 'Kura', code: 'KUR' },
    { name: 'Madobi', code: 'MAD' },
    { name: 'Makoda', code: 'MAK' },
    { name: 'Minjibir', code: 'MIN' },
    { name: 'Nasarawa', code: 'NAS' },
    { name: 'Rano', code: 'RAN' },
    { name: 'Rimin Gado', code: 'RIM' },
    { name: 'Rogo', code: 'ROG' },
    { name: 'Shanono', code: 'SHA' },
    { name: 'Sumaila', code: 'SUM' },
    { name: 'Takai', code: 'TAK' },
    { name: 'Tarauni', code: 'TAR' },
    { name: 'Tofa', code: 'TOF' },
    { name: 'Tsanyawa', code: 'TSA' },
    { name: 'Tudun Wada', code: 'TUW' },
    { name: 'Ungogo', code: 'UNG' },
    { name: 'Warawa', code: 'WAR' },
    { name: 'Wudil', code: 'WUD' },
  ] },
  { name: 'Katsina', code: 'KT', lgas: [
    { name: 'Bakori', code: 'BAK' },
    { name: 'Batagarawa', code: 'BAT' },
    { name: 'Batsari', code: 'BAS' },
    { name: 'Baure', code: 'BAU' },
    { name: 'Bindawa', code: 'BIN' },
    { name: 'Charanchi', code: 'CHA' },
    { name: 'Dandume', code: 'DAN' },
    { name: 'Danja', code: 'DAJ' },
    { name: 'Dan Musa', code: 'DAM' },
    { name: 'Daura', code: 'DAU' },
    { name: 'Dutsi', code: 'DUT' },
    { name: 'Dutsin Ma', code: 'DUM' },
    { name: 'Faskari', code: 'FAS' },
    { name: 'Funtua', code: 'FUN' },
    { name: 'Ingawa', code: 'ING' },
    { name: 'Jibia', code: 'JIB' },
    { name: 'Kafur', code: 'KAF' },
    { name: 'Kaita', code: 'KAI' },
    { name: 'Kankara', code: 'KAN' },
    { name: 'Kankia', code: 'KAK' },
    { name: 'Katsina', code: 'KAT' },
    { name: 'Kurfi', code: 'KUR' },
    { name: 'Kusada', code: 'KUS' },
    { name: 'Mai\'Adua', code: 'MAI' },
    { name: 'Malumfashi', code: 'MAL' },
    { name: 'Mani', code: 'MAN' },
    { name: 'Mashi', code: 'MAS' },
    { name: 'Matazu', code: 'MAT' },
    { name: 'Musawa', code: 'MUS' },
    { name: 'Rimi', code: 'RIM' },
    { name: 'Sabuwa', code: 'SAB' },
    { name: 'Safana', code: 'SAF' },
    { name: 'Sandamu', code: 'SAN' },
    { name: 'Zango', code: 'ZAN' },
  ] },
  { name: 'Kebbi', code: 'KE', lgas: [
    { name: 'Aleiro', code: 'ALE' },
    { name: 'Arewa Dandi', code: 'ARD' },
    { name: 'Argungu', code: 'ARG' },
    { name: 'Augie', code: 'AUG' },
    { name: 'Bagudo', code: 'BAG' },
    { name: 'Birnin Kebbi', code: 'BIK' },
    { name: 'Bunza', code: 'BUN' },
    { name: 'Dandi', code: 'DAN' },
    { name: 'Fakai', code: 'FAK' },
    { name: 'Gwandu', code: 'GWA' },
    { name: 'Jega', code: 'JEG' },
    { name: 'Kalgo', code: 'KAL' },
    { name: 'Koko/Besse', code: 'KOK' },
    { name: 'Maiyama', code: 'MAI' },
    { name: 'Ngaski', code: 'NGA' },
    { name: 'Sakaba', code: 'SAK' },
    { name: 'Shanga', code: 'SHA' },
    { name: 'Suru', code: 'SUR' },
    { name: 'Wasagu/Danko', code: 'WAS' },
    { name: 'Yauri', code: 'YAU' },
    { name: 'Zuru', code: 'ZUR' },
  ] },
  { name: 'Kogi', code: 'KO', lgas: [
    { name: 'Adavi', code: 'ADA' },
    { name: 'Ajaokuta', code: 'AJA' },
    { name: 'Ankpa', code: 'ANK' },
    { name: 'Bassa', code: 'BAS' },
    { name: 'Dekina', code: 'DEK' },
    { name: 'Ibaji', code: 'IBA' },
    { name: 'Idah', code: 'IDA' },
    { name: 'Igalamela Odolu', code: 'IGA' },
    { name: 'Ijumu', code: 'IJU' },
    { name: 'Kabba/Bunu', code: 'KAB' },
    { name: 'Koton Karfe', code: 'KOT' },
    { name: 'Lokoja', code: 'LOK' },
    { name: 'Mopa Muro', code: 'MOP' },
    { name: 'Ofu', code: 'OFU' },
    { name: 'Ogori/Magongo', code: 'OGO' },
    { name: 'Okehi', code: 'OKE' },
    { name: 'Okene', code: 'OKN' },
    { name: 'Olamaboro', code: 'OLA' },
    { name: 'Omala', code: 'OMA' },
    { name: 'Yagba East', code: 'YAE' },
    { name: 'Yagba West', code: 'YAW' },
  ] },
  { name: 'Kwara', code: 'KW', lgas: [
    { name: 'Asa', code: 'ASA' },
    { name: 'Baruten', code: 'BAR' },
    { name: 'Edu', code: 'EDU' },
    { name: 'Ekiti', code: 'EKI' },
    { name: 'Ifelodun', code: 'IFE' },
    { name: 'Ilorin East', code: 'ILE' },
    { name: 'Ilorin South', code: 'ILS' },
    { name: 'Ilorin West', code: 'ILW' },
    { name: 'Irepodun', code: 'IRE' },
    { name: 'Isin', code: 'ISI' },
    { name: 'Kaiama', code: 'KAI' },
    { name: 'Moro', code: 'MOR' },
    { name: 'Offa', code: 'OFF' },
    { name: 'Oke Ero', code: 'OKE' },
    { name: 'Oyun', code: 'OYU' },
    { name: 'Pategi', code: 'PAT' },
  ] },
  { name: 'Lagos', code: 'LA', lgas: [
    { name: 'Agege', code: 'AGE' },
    { name: 'Ajeromi-Ifelodun', code: 'AJI' },
    { name: 'Alimosho', code: 'ALI' },
    { name: 'Amuwo-Odofin', code: 'AMU' },
    { name: 'Apapa', code: 'APA' },
    { name: 'Badagry', code: 'BAD' },
    { name: 'Epe', code: 'EPE' },
    { name: 'Eti Osa', code: 'ETI' },
    { name: 'Ibeju-Lekki', code: 'IBE' },
    { name: 'Ifako-Ijaiye', code: 'IFA' },
    { name: 'Ikeja', code: 'IKE' },
    { name: 'Ikorodu', code: 'IKO' },
    { name: 'Kosofe', code: 'KOS' },
    { name: 'Lagos Island', code: 'LAI' },
    { name: 'Lagos Mainland', code: 'LAM' },
    { name: 'Mushin', code: 'MUS' },
    { name: 'Ojo', code: 'OJO' },
    { name: 'Oshodi-Isolo', code: 'OSH' },
    { name: 'Shomolu', code: 'SHO' },
    { name: 'Surulere', code: 'SUR' },
  ] },
  { name: 'Nasarawa', code: 'NA', lgas: [
    { name: 'Akwanga', code: 'AKW' },
    { name: 'Awe', code: 'AWE' },
    { name: 'Doma', code: 'DOM' },
    { name: 'Karu', code: 'KAR' },
    { name: 'Keana', code: 'KEA' },
    { name: 'Keffi', code: 'KEF' },
    { name: 'Kokona', code: 'KOK' },
    { name: 'Lafia', code: 'LAF' },
    { name: 'Nasarawa', code: 'NAS' },
    { name: 'Nasarawa Egon', code: 'NAE' },
    { name: 'Obi', code: 'OBI' },
    { name: 'Toto', code: 'TOT' },
    { name: 'Wamba', code: 'WAM' },
  ] },
  { name: 'Niger', code: 'NI', lgas: [
    { name: 'Agaie', code: 'AGA' },
    { name: 'Agwara', code: 'AGW' },
    { name: 'Bida', code: 'BID' },
    { name: 'Borgu', code: 'BOR' },
    { name: 'Bosso', code: 'BOS' },
    { name: 'Chanchaga', code: 'CHA' },
    { name: 'Edati', code: 'EDA' },
    { name: 'Gbako', code: 'GBA' },
    { name: 'Gurara', code: 'GUR' },
    { name: 'Katcha', code: 'KAT' },
    { name: 'Kontagora', code: 'KON' },
    { name: 'Lapai', code: 'LAP' },
    { name: 'Lavun', code: 'LAV' },
    { name: 'Magama', code: 'MAG' },
    { name: 'Mariga', code: 'MAR' },
    { name: 'Mashegu', code: 'MAS' },
    { name: 'Mokwa', code: 'MOK' },
    { name: 'Moya', code: 'MOY' },
    { name: 'Paikoro', code: 'PAI' },
    { name: 'Rafi', code: 'RAF' },
    { name: 'Rijau', code: 'RIJ' },
    { name: 'Shiroro', code: 'SHI' },
    { name: 'Suleja', code: 'SUL' },
    { name: 'Tafa', code: 'TAF' },
    { name: 'Wushishi', code: 'WUS' },
  ] },
  { name: 'Ogun', code: 'OG', lgas: [
    { name: 'Abeokuta North', code: 'ABN' },
    { name: 'Abeokuta South', code: 'ABS' },
    { name: 'Ado-Odo/Ota', code: 'ADO' },
    { name: 'Egbado North', code: 'EGN' },
    { name: 'Egbado South', code: 'EGS' },
    { name: 'Ewekoro', code: 'EWE' },
    { name: 'Ifo', code: 'IFO' },
    { name: 'Ijebu East', code: 'IJE' },
    { name: 'Ijebu North', code: 'IJN' },
    { name: 'Ijebu North East', code: 'IJN' },
    { name: 'Ijebu Ode', code: 'IJO' },
    { name: 'Ikenne', code: 'IKE' },
    { name: 'Imeko Afon', code: 'IME' },
    { name: 'Ipokia', code: 'IPO' },
    { name: 'Obafemi Owode', code: 'OBA' },
    { name: 'Odeda', code: 'ODE' },
    { name: 'Odogbolu', code: 'ODO' },
    { name: 'Ogun Waterside', code: 'OGW' },
    { name: 'Remo North', code: 'REN' },
    { name: 'Shagamu', code: 'SHA' },
  ] },
  { name: 'Ondo', code: 'ON', lgas: [
    { name: 'Akoko North-East', code: 'AKN' },
    { name: 'Akoko North-West', code: 'AKW' },
    { name: 'Akoko South-East', code: 'AKS' },
    { name: 'Akoko South-West', code: 'AKW' },
    { name: 'Akure North', code: 'AKN' },
    { name: 'Akure South', code: 'AKS' },
    { name: 'Ese Odo', code: 'ESE' },
    { name: 'Idanre', code: 'IDA' },
    { name: 'Ifedore', code: 'IFE' },
    { name: 'Ilaje', code: 'ILA' },
    { name: 'Ile Oluji/Okeigbo', code: 'ILE' },
    { name: 'Irele', code: 'IRE' },
    { name: 'Odigbo', code: 'ODI' },
    { name: 'Okitipupa', code: 'OKI' },
    { name: 'Ondo East', code: 'ONE' },
    { name: 'Ondo West', code: 'ONW' },
    { name: 'Ose', code: 'OSE' },
    { name: 'Owo', code: 'OWO' },
  ] },
  { name: 'Osun', code: 'OS', lgas: [
    { name: 'Aiyedaade', code: 'AIY' },
    { name: 'Aiyedire', code: 'AID' },
    { name: 'Atakumosa East', code: 'ATE' },
    { name: 'Atakumosa West', code: 'ATW' },
    { name: 'Boluwaduro', code: 'BOL' },
    { name: 'Boripe', code: 'BOR' },
    { name: 'Ede North', code: 'EDN' },
    { name: 'Ede South', code: 'EDS' },
    { name: 'Egbedore', code: 'EGB' },
    { name: 'Ejigbo', code: 'EJI' },
    { name: 'Ife Central', code: 'IFC' },
    { name: 'Ife East', code: 'IFE' },
    { name: 'Ife North', code: 'IFN' },
    { name: 'Ife South', code: 'IFS' },
    { name: 'Ifedayo', code: 'IFD' },
    { name: 'Ifelodun', code: 'IFL' },
    { name: 'Ila', code: 'ILA' },
    { name: 'Ilesa East', code: 'ILE' },
    { name: 'Ilesa West', code: 'ILW' },
    { name: 'Irepodun', code: 'IRE' },
    { name: 'Irewole', code: 'IRW' },
    { name: 'Isokan', code: 'ISO' },
    { name: 'Iwo', code: 'IWO' },
    { name: 'Obokun', code: 'OBO' },
    { name: 'Odo Otin', code: 'ODO' },
    { name: 'Ola Oluwa', code: 'OLA' },
    { name: 'Olorunda', code: 'OLU' },
    { name: 'Oriade', code: 'ORI' },
    { name: 'Orolu', code: 'ORO' },
    { name: 'Osogbo', code: 'OSO' },
  ]},
  { name: 'Oyo', code: 'OY', lgas: [
    { name: 'Afijio', code: 'AFI' },
    { name: 'Akinyele', code: 'AKI' },
    { name: 'Atiba', code: 'ATI' },
    { name: 'Atisbo', code: 'ATS' },
    { name: 'Egbeda', code: 'EGB' },
    { name: 'Ibadan North', code: 'IBN' },
    { name: 'Ibadan North-East', code: 'IBN' },
    { name: 'Ibadan North-West', code: 'IBW' },
    { name: 'Ibadan South-East', code: 'IBS' },
    { name: 'Ibadan South-West', code: 'IBW' },
    { name: 'Ibarapa Central', code: 'IBC' },
    { name: 'Ibarapa East', code: 'IBE' },
    { name: 'Ibarapa North', code: 'IBN' },
    { name: 'Ido', code: 'IDO' },
    { name: 'Irepo', code: 'IRE' },
    { name: 'Iseyin', code: 'ISE' },
    { name: 'Itesiwaju', code: 'ITE' },
    { name: 'Iwajowa', code: 'IWA' },
    { name: 'Kajola', code: 'KAJ' },
    { name: 'Lagelu', code: 'LAG' },
    { name: 'Ogbomosho North', code: 'OGN' },
    { name: 'Ogbomosho South', code: 'OGS' },
    { name: 'Ogo Oluwa', code: 'OGO' },
    { name: 'Olorunsogo', code: 'OLR' },
    { name: 'Oluyole', code: 'OLU' },
    { name: 'Ona Ara', code: 'ONA' },
    { name: 'Orelope', code: 'ORE' },
    { name: 'Ori Ire', code: 'ORI' },
    { name: 'Oyo', code: 'OYO' },
    { name: 'Oyo East', code: 'OYE' },
    { name: 'Saki East', code: 'SAE' },
    { name: 'Saki West', code: 'SAW' },
    { name: 'Surulere', code: 'SUR' },
  ]},
  { name: 'Plateau', code: 'PL', lgas: [
    { name: 'Barkin Ladi', code: 'BAR' },
    { name: 'Bassa', code: 'BAS' },
    { name: 'Bokkos', code: 'BOK' },
    { name: 'Jos East', code: 'JOE' },
    { name: 'Jos North', code: 'JON' },
    { name: 'Jos South', code: 'JOS' },
    { name: 'Kanam', code: 'KAN' },
    { name: 'Kanke', code: 'KAK' },
    { name: 'Langtang North', code: 'LAN' },
    { name: 'Langtang South', code: 'LAS' },
    { name: 'Mangu', code: 'MAN' },
    { name: 'Mikang', code: 'MIK' },
    { name: 'Pankshin', code: 'PAN' },
    { name: 'Qua\'an Pan', code: 'QUA' },
    { name: 'Riyom', code: 'RIY' },
    { name: 'Shendam', code: 'SHE' },
    { name: 'Wase', code: 'WAS' },
  ]},
  { name: 'Rivers', code: 'RI', lgas: [
    { name: 'Abua/Odual', code: 'ABU' },
    { name: 'Ahoada East', code: 'AHE' },
    { name: 'Ahoada West', code: 'AHW' },
    { name: 'Akuku Toru', code: 'AKU' },
    { name: 'Andoni', code: 'AND' },
    { name: 'Asari-Toru', code: 'ASA' },
    { name: 'Bonny', code: 'BON' },
    { name: 'Degema', code: 'DEG' },
    { name: 'Eleme', code: 'ELE' },
    { name: 'Emohua', code: 'EMO' },
    { name: 'Etche', code: 'ETC' },
    { name: 'Gokana', code: 'GOK' },
    { name: 'Ikwerre', code: 'IKW' },
    { name: 'Khana', code: 'KHA' },
    { name: 'Obio/Akpor', code: 'OBI' },
    { name: 'Ogba/Egbema/Ndoni', code: 'OGB' },
    { name: 'Ogu/Bolo', code: 'OGU' },
    { name: 'Okrika', code: 'OKR' },
    { name: 'Omuma', code: 'OMU' },
    { name: 'Opobo/Nkoro', code: 'OPO' },
    { name: 'Oyigbo', code: 'OYI' },
    { name: 'Port Harcourt', code: 'POR' },
    { name: 'Tai', code: 'TAI' },
  ]},
  { name: 'Sokoto', code: 'SO', lgas: [
    { name: 'Binji', code: 'BIN' },
    { name: 'Bodinga', code: 'BOD' },
    { name: 'Dange Shuni', code: 'DAN' },
    { name: 'Gada', code: 'GAD' },
    { name: 'Goronyo', code: 'GOR' },
    { name: 'Gudu', code: 'GUD' },
    { name: 'Gwadabawa', code: 'GWA' },
    { name: 'Illela', code: 'ILL' },
    { name: 'Isa', code: 'ISA' },
    { name: 'Kebbe', code: 'KEB' },
    { name: 'Kware', code: 'KWA' },
    { name: 'Rabah', code: 'RAB' },
    { name: 'Sabon Birni', code: 'SAB' },
    { name: 'Shagari', code: 'SHA' },
    { name: 'Silame', code: 'SIL' },
    { name: 'Sokoto North', code: 'SON' },
    { name: 'Sokoto South', code: 'SOS' },
    { name: 'Tambuwal', code: 'TAM' },
    { name: 'Tangaza', code: 'TAN' },
    { name: 'Tureta', code: 'TUR' },
    { name: 'Wamako', code: 'WAM' },
    { name: 'Wurno', code: 'WUR' },
    { name: 'Yabo', code: 'YAB' },
  ]},
  { name: 'Taraba', code: 'TA', lgas: [
    { name: 'Ardo Kola', code: 'ARD' },
    { name: 'Bali', code: 'BAL' },
    { name: 'Donga', code: 'DON' },
    { name: 'Gashaka', code: 'GAS' },
    { name: 'Gassol', code: 'GAS' },
    { name: 'Ibi', code: 'IBI' },
    { name: 'Jalingo', code: 'JAL' },
    { name: 'Karim Lamido', code: 'KAR' },
    { name: 'Kumi', code: 'KUM' },
    { name: 'Lau', code: 'LAU' },
    { name: 'Sardauna', code: 'SAR' },
    { name: 'Takum', code: 'TAK' },
    { name: 'Ussa', code: 'USS' },
    { name: 'Wukari', code: 'WUK' },
    { name: 'Yorro', code: 'YOR' },
    { name: 'Zing', code: 'ZIN' },
  ]},
  { name: 'Yobe', code: 'YO', lgas: [
    { name: 'Bade', code: 'BAD' },
    { name: 'Bursari', code: 'BUR' },
    { name: 'Damaturu', code: 'DAM' },
    { name: 'Fika', code: 'FIK' },
    { name: 'Fune', code: 'FUN' },
    { name: 'Geidam', code: 'GEI' },
    { name: 'Gujba', code: 'GUJ' },
    { name: 'Gulani', code: 'GUL' },
    { name: 'Jakusko', code: 'JAK' },
    { name: 'Karasuwa', code: 'KAR' },
    { name: 'Machina', code: 'MAC' },
    { name: 'Nangere', code: 'NAN' },
    { name: 'Nguru', code: 'NGU' },
    { name: 'Potiskum', code: 'POT' },
    { name: 'Tarmuwa', code: 'TAR' },
    { name: 'Yunusari', code: 'YUN' },
    { name: 'Yusufari', code: 'YUS' },
  ]},
  { name: 'Zamfara', code: 'ZA', lgas: [
    { name: 'Anka', code: 'ANK' },
    { name: 'Bakura', code: 'BAK' },
    { name: 'Birnin Magaji/Kiyaw', code: 'BIR' },
    { name: 'Bukkuyum', code: 'BUK' },
    { name: 'Bungudu', code: 'BUN' },
    { name: 'Gummi', code: 'GUM' },
    { name: 'Gusau', code: 'GUS' },
    { name: 'Kaura Namoda', code: 'KAU' },
    { name: 'Maradun', code: 'MAR' },
    { name: 'Maru', code: 'MAU' },
    { name: 'Shinkafi', code: 'SHI' },
    { name: 'Talata Mafara', code: 'TAL' },
    { name: 'Chafe', code: 'CHA' },
    { name: 'Zurmi', code: 'ZUR' },
  ]}
];

export function getStateCode(stateName: string): string | undefined {
  const state = NIGERIA_STATES.find(
    s => s.name.toLowerCase() === stateName.toLowerCase()
  );
  return state?.code;
}

export function getLgaCode(stateName: string, lgaName: string): string | undefined {
  const state = NIGERIA_STATES.find(
    s => s.name.toLowerCase() === stateName.toLowerCase()
  );
  if (!state) return undefined;
  const lga = state.lgas.find(
    l => l.name.toLowerCase() === lgaName.toLowerCase()
  );
  return lga?.code;
} 