version: '3.8'

services:
  test-db:
    image: postgres:15
    container_name: trustfund_test_db
    environment:
      POSTGRES_DB: trustfund_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data: 