apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-inv2-postgres
  namespace: inv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inv2-postgres
  template:
    metadata:
      labels:
        app: inv2-postgres
    spec:
      containers:
        - name: inv2-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inv2_db
            - name: POSTGRES_USER
              value: inv2_usr
            - name: POSTGRES_PASSWORD
              value: inv2_pwd
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "inv2-pgdata"
      volumes:
        - hostPath:
            path: "/home/inv2/pgdata"
          name: inv2-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: inv2-postgres-srv
  namespace: inv2
spec:
  selector:
    app: inv2-postgres
  ports:
    - name: inv2-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
