apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-backend
  namespace: trustfund
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # image: trustfundregistry.azurecr.io/demo/backend
          image: integrationschd/trustfund-backend
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BACKEND_BASE
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: BACKEND_BASE
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_TIME
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: ACCESS_TOKEN_TIME
            - name: AES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: AES_SECRET_KEY
            - name: RABBITMQ
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: RABBITMQ
            - name: REDIS_SERVER
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: REDIS_SERVER
            - name: MAIL_ZEPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: MAIL_ZEPTO_KEY
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: PORT
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: CORS_ALLOWED_ORIGINS
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_URL
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: CLOUDINARY_URL
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_USERNAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_PORT
            - name: DB_DIALECT
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_DIALECT
            - name: DB_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_SCHEMA_NAME
            - name: DB_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: DB_TIMEZONE
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: JWT_REFRESH_TOKEN_SECRET
            - name: JWT_ACCESS_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: JWT_ACCESS_TOKEN_EXPIRY
            - name: JWT_REFRESH_TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: JWT_REFRESH_TOKEN_EXPIRY
            - name: TRUSTFUND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_USERNAME
            - name: TRUSTFUND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_PASSWORD
            - name: TRUSTFUND_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_BASE_URL
            - name: TRUSTFUND_URL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_URL
            - name: TRUSTFUND_EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_EMAIL_FROM
            - name: TRUSTFUND_EMAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_EMAIL_FROM_NAME
            - name: TRUSTFUND_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_SERVICE_URL
            - name: TRUSTFUND_SMS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_SMS_USERNAME
            - name: TRUSTFUND_SMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_SMS_PASSWORD
            - name: TRUSTFUND_SMS_SENDER
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: TRUSTFUND_SMS_SENDER
            - name: QOREID_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: QOREID_BASE_URL
            - name: QOREID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: QOREID_CLIENT_ID
            - name: QOREID_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: QOREID_SECRET
            - name: VERIFYME_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: VERIFYME_BASE_URL
            - name: VERIFYME_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: VERIFYME_SECRET_KEY
            - name: SUPPORT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: SUPPORT_EMAIL
            - name: SUPPORT_PHONE
              valueFrom:
                secretKeyRef:
                  name: backend.depl
                  key: SUPPORT_PHONE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  namespace: trustfund
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 3001
      targetPort: 3001
