apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-payment
  namespace: inv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          # image: inv2registry.azurecr.io/demo/payment
          image: integrationschd/inv2-payment
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BACKEND_BASE
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: BACKEND_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
  namespace: inv2
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3001
      targetPort: 3001
