apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-saveplan
  namespace: inv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saveplan
  template:
    metadata:
      labels:
        app: saveplan
    spec:
      containers:
        - name: saveplan
          # image: inv2registry.azurecr.io/demo/saveplan
          image: integrationschd/inv2-saveplan
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BACKEND_BASE
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: BACKEND_BASE
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_TIME
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: ACCESS_TOKEN_TIME
            - name: AES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: AES_SECRET_KEY
            - name: RABBITMQ
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: RABBITMQ
            - name: REDIS_SERVER
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: REDIS_SERVER
            - name: MAIL_ZEPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: MAIL_ZEPTO_KEY
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: PORT
            - name: DB_PG_HOST
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_HOST
            - name: DB_PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_DB_NAME
            - name: DB_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_PASSWORD
            - name: DB_PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_USERNAME
            - name: DB_PG_PORT
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_PORT
            - name: DB_PG_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: saveplan.depl
                  key: DB_PG_TIMEZONE
---
apiVersion: v1
kind: Service
metadata:
  name: saveplan-srv
  namespace: inv2
spec:
  selector:
    app: saveplan
  ports:
    - name: saveplan
      protocol: TCP
      port: 3001
      targetPort: 3001
