apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-web-admin
  namespace: trustfund
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin
  template:
    metadata:
      labels:
        app: web-admin
    spec:
      containers:
        - name: web-admin
          image: integrationschd/trustfund-web-admin
---
apiVersion: v1
kind: Service
metadata:
  name: web-admin-srv
  namespace: trustfund
spec:
  selector:
    app: web-admin
  ports:
    - name: web-admin
      protocol: TCP
      port: 80
      targetPort: 80
