name: Deploy Staging To DigitalOceans

on:
  push:
    branches:
      - 'staging'
    paths:
      - 'Backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cd Backend && docker build -t integrationschd/trustfund-backend .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push integrationschd/trustfund-backend
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: staging
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save trustfund
      - run: kubectl rollout restart deployment depl-backend -n trustfund