name: Deploy Manifests to Prod

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@master
        name: Create Pem file and connect to Prod
        with:
          host: ${{ secrets.AWS_HOST }}
          key: ${{ secrets.AWS_SSH_KEY }}
          username: ${{ secrets.AWS_USER }}
          script: |
            git clone https://github.com/InvestNaija/TrustFundPension.git
            cd TrustFundPension
            kubectl apply -f infra/k8s -n trustfund && kubectl apply -f infra/k8s-prod -n trustfund
            cd ..
            sudo rm -r trustfund
            