name: Deploy Manifests to Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save trustfund
      - run: kubectl apply -f infra/k8s -n trustfund && kubectl apply -f infra/k8s-staging -n trustfund
